name: webhookapp
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.local
    container_name: webhookapp-app
    restart: always
    healthcheck:
      test: ["CMD", "symfony", "server:status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
        - webhookappdev

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portobello}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-portobello}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: always
    container_name: webhookapp-db
    networks:
        - webhookappdev

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: php bin/console messenger:consume async --time-limit=3600
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file: .env.local
    restart: always
    container_name: webhookapp-worker
    networks:
        - webhookappdev

volumes:
  database_data:

networks:
  webhookappdev:
    name: webhookappdev
