name: hookyard
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: hookyard_php
      args:
        APP_ENV: dev
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    env_file: .env.local
    container_name: hookyard-app
    restart: always
    healthcheck:
      test: ["CMD", "symfony", "server:status"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
        - hookyarddev

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
      target: hookyard_nginx
    volumes:
      - .:/usr/share/nginx/html:ro
    ports:
      - "8000:80"
    depends_on:
      app:
        condition: service_healthy
    restart: always
    container_name: hookyard-nginx
    networks:
        - hookyarddev

  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-portobello}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-portobello}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: always
    container_name: hookyard-db
    networks:
        - hookyarddev

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: hookyard_node
    working_dir: /app/frontend
    volumes:
      - .:/app
    command: npm run watch
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    networks:
      - hookyarddev

  worker:
    build:
      context: .
      dockerfile: Dockerfile
      target: hookyard_php
      args:
        APP_ENV: dev
    volumes:
      - .:/app
    command: php bin/console messenger:consume async --time-limit=3600 --no-debug
    depends_on:
      app:
        condition: service_healthy
      db:
        condition: service_healthy
    env_file: .env.local
    restart: always
    container_name: hookyard-worker
    networks:
        - hookyarddev

volumes:
  database_data:

networks:
  hookyarddev:
    name: hookyarddev
