<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260430163753 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Fix request_usage.id to use IDENTITY so raw DBAL inserts auto-generate the PK';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE request_usage ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE request_usage ALTER id DROP IDENTITY');
    }
}
