# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

api_v1:
    resource: ../src/Controller/Api/v1
    prefix: /api/v1
    name_prefix: api_v1_
    type: attribute

ingest:
    resource: ../src/Controller/IngestEventController.php
    prefix: /
    type: attribute

spa:
    resource: ../src/Controller/SpaController.php
    prefix: /
    type: attribute
