[program:queue]
command=php /app/bin/console messenger:consume async --time-limit=3600 --no-debug
directory=/app
user=root
numprocs=1
autostart=true
autorestart=true
startsecs=0
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/supervisor/queue.log
stderr_logfile=/var/log/supervisor/queue-error.log
