[program:scheduler]
command=php /app/bin/console messenger:consume scheduler_prune-request-usage
directory=/app
user=root
numprocs=1
autostart=true
autorestart=true
startsecs=0
process_name=%(program_name)s_%(process_num)02d
stdout_logfile=/var/log/supervisor/scheduler.log
stderr_logfile=/var/log/supervisor/scheduler-error.log
